"""Phase 1 (worker action segmentation) configuration."""
from __future__ import annotations

from pathlib import Path
from src.config.common import DATA_DIR

# --- paths -------------------------------------------------------------------
WORKER_VIDEO = DATA_DIR / "worker.mp4"
KINEMATIC_OUT_DIR = DATA_DIR / "kinematic"
REPORT_PATH = KINEMATIC_OUT_DIR / "pipe1_report.json"
BOUNDARIES_PATH = KINEMATIC_OUT_DIR / "action_boundaries_dynamic.npy"
MASKS_PATH = KINEMATIC_OUT_DIR / "worker_masks.npz"
FLOW_PATH = KINEMATIC_OUT_DIR / "worker_flow.npz"
ACTION_SEGMENTS_PATH = KINEMATIC_OUT_DIR / "action_segments.json"  # phase output, read by Phase 2

# --debug / --visualize output (annotated video + boundary plots from the kinematic sub-pipeline) --
DEBUG_DIR = KINEMATIC_OUT_DIR / "debug"

# Fallback paths if generated by the kinematic sub-pipeline's own output dir directly
KINEMATIC_PIPELINE_DIR = Path(__file__).resolve().parents[1] / "kinematic_pipeline"
KINEMATIC_PIPELINE_OUTPUT = KINEMATIC_PIPELINE_DIR / "output" / "video_worker"

# backwards-compatible aliases
SEGMENT_FLOW_DIR = KINEMATIC_PIPELINE_DIR
SEGMENT_FLOW_OUTPUT = KINEMATIC_PIPELINE_OUTPUT

# --- kinematic segmentation tunables -----------------------------------------
ANGLE_TOLERANCE = 60.0       # deg: direction change threshold
MIN_SEGMENT_LEN = 20         # frames: min duration before boundary (at ~30fps -> ~0.66s)
MIN_DISTANCE = 0.6           # sec: min distance between speed peaks/valleys
PROMINENCE = 0.25            # relative prominence threshold for speed valleys
SMOOTH_WINDOW = 9            # Savgol window for magnitude smoothing
REQUIRE_BOTH = True          # require both speed valley and direction shift (or idle resume)
